include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/generated/**"
    - "**/build/**"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.g.dart"
    - "**/*.iconfig.dart"
    - "**/*.p.dart"
    - "**/*.r.dart"
    - "**/*.reflectable.dart"
    - "**/*.seeds.dart"
    - "**/*.template.dart"
    - "**/*.theme.dart"
    - "**/*.w.dart"
    - "**/*.watch"

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else