name: flueco

packages:
  - packages/*
  - example
scripts:
  format:check:
    exec: dart format --output=none --set-exit-if-changed .
  format:fix:
    exec: dart format .
  analyze:example:
    exec: dart analyze .
    packageFilters:
      scope: '*example*'
  analyze:packages:
    exec: dart analyze .
    packageFilters:
      scope: '*flueco*'
  analyze:all:
    exec: dart analyze .
  test:
    exec: flutter test
    packageFilters:
      scope: '*flueco*'
  upgrade:
    exec: flutter pub upgrade
    packageFilters:
      scope: '*flueco*'
  upgrade-major:
    exec: flutter pub upgrade --major-versions
    packageFilters:
      scope: '*flueco*'
  install:
    exec: flutter pub get --no-example
  outdated:
    exec: flutter pub outdated --no-transitive
  version:check:
    exec: melos version --no-git-tag-version --no-git-commit-version
  publish:validate:
    exec: melos clean && melos publish --dry-run
  publish:run:
    exec: melos clean && melos publish --no-dry-run --no-git-tag-version
  clean-bs:
    exec: melos clean && melos bs
  remove-pubspec-lock:
    exec: rm pubspec.lock
    packageFilters:
      scope: '*flueco*'
  clean:deep:
    steps:
      - clean
      - melos exec -- "flutter clean"
      - melos exec -- "rm pubspec.lock"