name: flueco_auth
description: Flueco Tool for authentication using different strategies through providers. 
version: 0.0.1-alpha.6
repository: https://github.com/flutter-ecosystem/flueco

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flueco_core: ^0.0.1-alpha.5

dev_dependencies:
  lints: ^5.1.1
  test: ^1.21.0
