name: "🐞 Bug Report"
description: "Report a reproducible bug or regression."
title: "[ISSUE] [<package>] <short description>"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Please fill out all required sections to help us address your issue quickly.
        Replace `<package>` with the name of the package where the bug occurs.
        If you are not sure which package, use `flueco` as a default.

  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "A clear and concise description of what the bug is."
      placeholder: "e.g. App crashes when clicking login button"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the behavior."
      placeholder: "1. Go to ...\n2. Click on ...\n3. See error ..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "It should ..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "It actually ..."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Package/Repo Version"
      description: "What version(s) are you using?"
      placeholder: "e.g. flueco_core 1.2.3"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "OS, Flutter/Dart version, device, etc."
      placeholder: "e.g. Windows 11, Flutter 3.19.0, Android 14, ..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Relevant Logs/Stacktrace"
      description: "Paste any relevant logs or stack traces."
      render: shell
      placeholder: "Paste logs here"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes"
      description: "Anything else we should know?"
      placeholder: "Optional"
    validations:
      required: false
