name: flueco_auth_token
description: "Flueco Authentication package"
version: 0.0.1-alpha.2
repository: https://github.com/flutter-ecosystem/flueco

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flueco_core: ^0.0.1-alpha.2
  flueco_auth: ^0.0.1-alpha.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
