name: flueco_auth_token
description: "Flueco Authentication provider package for token authentication"
version: 0.0.1-alpha.6
repository: https://github.com/flutter-ecosystem/flueco

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flueco_core: ^0.0.1-alpha.5
  flueco_auth: ^0.0.1-alpha.5

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
