// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:example/data/sources/local/db/models/user_model.dart';
import 'package:example/data/sources/local/db/models/user_profile_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(UserDBAdapter());
    registerAdapter(UserProfileDBAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(UserDBAdapter());
    registerAdapter(UserProfileDBAdapter());
  }
}
