name: flueco_auth_dio_interceptor
description: Interceptor for Dio and Flueco Auth to authenticate requests.
version: 0.0.1-alpha.4
repository: https://github.com/flutter-ecosystem/flueco

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  dio: ^5.4.0
  flueco_core: ^0.0.1-alpha.5
  flueco_auth: ^0.0.1-alpha.4
  flueco_dio: ^0.0.1-alpha.4

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
