name: flueco_auth_dio_interceptor
description: Interceptor for Dio and Flueco Auth to authenticate requests.
version: 0.0.1-alpha
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  dio: ^5.4.0
  flueco_core:
    git:
      url: https://github.com/flutter-ecosystem/flueco.git
      ref: main
      path: packages/flueco_core
  flueco_auth:
    git:
      url: https://github.com/flutter-ecosystem/flueco.git
      ref: main
      path: packages/flueco_auth
  flueco_dio:
    git:
      url: https://github.com/flutter-ecosystem/flueco.git
      ref: main
      path: packages/flueco_dio

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
