name: Check Commit Message and Branch Name Style

on:
  workflow_run:
    workflows: ["Check PR Assignee and Label"]
    types:
      - completed

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all commits in the PR
        id: commits
        run: |
          git fetch origin ${{ github.base_ref }}
          git log origin/${{ github.base_ref }}..HEAD --pretty=format:'%s' > commit_messages.txt

      - name: Check commit messages for Conventional Commits
        run: |
          regex='^((feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(\([a-zA-Z0-9_-]+\))?: .+|Merge branch .+|Merge pull request .+)$'
          while IFS= read -r line; do
            if ! [[ $line =~ $regex ]]; then
              echo "❌ Commit message does not follow Conventional Commits or merge commit style: $line"
              exit 1
            fi
          done < commit_messages.txt
          echo "✅ All commit messages follow Conventional Commits or are valid merge commits."

      - name: Check branch name style
        run: |
          branch_name="${{ github.head_ref }}"
          branch_regex='^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)\/[a-zA-Z0-9._\/-]+$'
          if ! [[ $branch_name =~ $branch_regex ]]; then
            echo "❌ Branch name does not follow required style: $branch_name"
            echo "Branch name must start with one of: feat/, fix/, chore/, docs/, style/, refactor/, perf/, test/, build/, ci/, revert/"
            exit 1
          fi
          echo "✅ Branch name follows required style."
