name: Check Analyze, Format, and Test

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  workflow_run:
    workflows: ["Check Commit Message and Branch Name Style"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Verify Flutter version
        run: flutter --version

      - name: Install melos globally
        run: dart pub global activate melos

      - name: Install dependencies
        run: dart pub get --no-example && melos bs

      - name: Verify formatting on every package
        run: melos run format:check

      - name: Analyze project source of every package
        run: melos run analyze:all

      - name: Run tests on every package
        run: melos run test
