# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Push on main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Verify Flutter version
        run: flutter --version

      - name: Install melos globally
        run: dart pub global activate melos

      - name: Install dependencies
        run: melos bs

      - name: Verify formatting on every package
        run: melos run format:check

      - name: Analyze project source of every package
        run: melos run analyze:all

      - name: Run tests on every package
        run: melos run test
